version: '2'

services:
    mysql:
        image: mariadb:10.4
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        container_name: helloworld_mysql

    php-fpm:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ../app:/app
        container_name: helloworld_php

    nginx:
        image: nginx:1.16
        ports:
            - 80:80
        volumes_from:
            - php-fpm
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./.data/logs/nginx:/var/log/nginx
        container_name: helloworld_nginx
